// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Pet struct {
	ID   int64   `json:"id"`
	Name string  `json:"name"`
	Tag  *string `json:"tag,omitempty"`
}
