// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"petstore/internal/sdk/pkg/models/shared"
)

type ShowPetByIDRequest struct {
	// The id of the pet to retrieve
	PetID string `pathParam:"style=simple,explode=false,name=petId"`
}

type ShowPetByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// unexpected error
	Error *shared.Error
	// Expected response to a valid request
	Pet *shared.Pet
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
